import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
    container: {
        backgroundColor: '#FFFFFF',
    },
    content: {
        flex: 1,
        flexDirection: 'column',
        width: '90%',
        maxWidth: 400,
        alignSelf: 'center',
        backgroundColor: '#D8F6F5',
        borderRadius: 23,
        marginTop: 20,
        padding: 20,
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.25,
                shadowRadius: 3.84,
            },
            android: {
                elevation: 5,
            },
        }),
    },
    image: {
        flex: 1,
        resizeMode: 'stretch',
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
        marginBottom: 30,
    },
    h1: {
        fontSize: 26,
        fontFamily: 'bold',
        color: '#293772',
        marginTop: 20,
        textAlign: 'center',
    },
    h3: {
        fontSize: 22,
        fontFamily: 'bold',
        color: '#293772',
        marginBottom: 16,
    },
    checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 10,
        marginLeft: -15,
    },
    text: {
        fontSize: 16,
        color: '#2C2C2C',
        marginBottom: 16,
        marginTop: 18,
        marginLeft: 20,
        textAlign: 'left',
    },
    lienRetour: {
        position: 'absolute',
        left: 2,
        marginVertical: -3,
        paddingVertical: -15,
        marginLeft: 30,
        fontSize: 18,
        color: '#2C2C2C',
        textDecorationLine: 'underline',
        lineHeight: 22,
        textAlign: 'left',
    },
    label: {
        fontSize: 16,
        color: '#272727',
        lineHeight: 19,
        marginBottom: 10,
        marginTop: 18,
        paddingHorizontal: 10,
    },
    inputwrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    inputcontent: {
        flex: 1,
        fontSize: 16,
        color: '#707070',
        lineHeight: 19,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#707070',
        borderRadius: 8,
        height: 52,
        padding: 10,
    },
    passwordInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    passwordInputContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    passwordInput: {
        flex: 1,
        fontSize: 16,
        color: '#707070',
        lineHeight: 19,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#707070',
        borderRadius: 8,
        height: 52,
        padding: 10,
    },
    icon: {
        position: 'absolute',
        color: '#000000',
        fontSize: 15,
        left: 15,
    },
    iconRight: {
        position: 'absolute',
        color: '#000000',
        fontSize: 15,
        right: 15,
        textAlign: 'right',
    },
    passwordIcon: {
        position: 'absolute',
        color: '#000000',
        fontSize: 24,
        textAlign: 'right',
        right: 15,
    },
    textbuttom: {
        fontSize: 16,
        color: '#242F65',
        lineHeight: 19,
        textAlign: 'center',
    },
    buttom: {
        backgroundColor: '#65D9D6',
        borderWidth: 1,
        borderColor: '#65D9D6',
        borderRadius: 8,
        width: 148,
        height: 43,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: -12,
        marginRight: 20,
    },
});

export default styles;
