import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        width: '100%',
        height: '100%',
        backgroundColor: '#FFFFFF',
    },
    content: {
        flexDirection: 'column',
        width: 356,
        backgroundColor: '#D8F6F5',
        borderRadius: 23,
        opacity: 1,
        marginTop: 20,
        padding: 20,
        alignSelf: 'center',
    },
    h1: {
        fontSize: 24,
        fontFamily: 'bold',
        color: '#293772',
        lineHeight: 29,
        marginTop: 17,
        textAlign: 'center',
        marginLeft: 60,
        marginRight: 60,
    },
    text: {
        fontFamily: 'regular',
        fontSize: 15,
        color: '#2C2C2C',
        marginBottom: 16,
        marginTop: 18,
        marginLeft: 20,
        textAlign: 'left',
    },
    textimage: {
        fontFamily: 'medium',
        fontSize: 15,
        color: '#242F65',
        lineHeight: 19,
        textAlign: 'center',
    },
    label: {
        fontFamily: 'regular',
        fontSize: 15,
        color: '#272727',
        lineHeight: 19,
        marginBottom: 10,
        marginTop: 18,
        paddingHorizontal: 10,
    },
    uploadedImage: {
        width: '100%',
        height: '100%',
        borderRadius: 8,
    },
    inputimage: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: 232,
        height: 55,
        position: 'absolute',
        backgroundColor: '#FFFFFF',
        borderColor: '#242F65',
        borderWidth: 1,
        borderRadius: 8,
        padding: 16,
        opacity: 1,
    },
    inputimagewrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
        width: 312,
        height: 112,
        backgroundColor: '#FFFFFF',
        borderColor: '#242F65',
        borderWidth: 1,
        borderRadius: 8,
        borderStyle: 'dashed',
        padding: 16,
        opacity: 1,
    },
    inputwrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    inputcontent: {
        flex: 1,
        fontFamily: 'regular',
        fontSize: 16,
        color: '#707070',
        lineHeight: 19,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#707070',
        borderRadius: 8,
        opacity: 1,
        height: 52,
        padding: 10,
    },
    passwordInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    passwordInputContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    passwordInput: {
        flex: 1,
        fontFamily: 'regular',
        fontSize: 16,
        color: '#707070',
        lineHeight: 19,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#707070',
        borderRadius: 8,
        opacity: 1,
        height: 52,
        padding: 10,
    },
    pickerSelect: {
        fontSize: 16,
        paddingVertical: 12,
        paddingHorizontal: 10,
        color: 'black',
    },
    passwordIcon: {
        position: 'absolute',
        color: '#000000',
        fontSize: 24,
        textAlign: 'right',
        right: 15,
        zIndex: 1,
        marginTop: -11,
    },
    icon:{
        flexDirection: 'column',
        alignItems: 'flex-end',
        color:'#242F65',
        Size:30,
        right:10,
        position:"absolute",
        marginTop:18,
        marginRight:13
    },
    iconLeft:{
        color:'#242F65',
        fontSize:26,
        marginTop:15,
        marginLeft:15,
        fontFamily:'bold',
        alignSelf:'flex-start',
        position:'absolute'
    },
    iconplus: {
        position: 'relative',
        fontSize: 24,
        color: '#242F65',
        marginRight: 8,
    },
    textbuttom: {
        fontFamily: 'medium',
        fontSize: 16,
        color: '#242F65',
        lineHeight: 19,
        textAlign: 'center',
    },
    buttom: {
        backgroundColor: '#65D9D6',
        borderWidth: 1,
        borderColor: '#65D9D6',
        borderRadius: 8,
        opacity: 1,
        width: 148,
        height: 43,
        flexDirection: 'row',
        alignContent: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: -12,
        marginRight: 20,
        marginBottom: 10,
    },
    lienRetour: {
        position: 'absolute',
        left: 2,
        marginVertical: -3,
        paddingVertical: -15,
        marginLeft: 30,
        fontFamily: 'regular',
        fontSize: 18,
        color: '#2C2C2C',
        textDecorationLine: 'underline',
        lineHeight: 22,
        textAlign: 'left',
    },
    ajouterwrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        marginTop: 15,
        marginBottom: 10,
        width: 310,
        height: 60,
        backgroundColor: '#FFFFFF',
        borderColor: '#242F65',
        borderWidth: 1,
        borderRadius: 8,
        padding: 16,
        opacity: 1,
    }
});

export default styles;
